# color-scheme
[[plugins]]
repo = 'overcache/NeoSolarized'
[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
# 補完をするため
repo = 'vim-denops/denops.vim'

# ステータスをいい感じに表示
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'vim-airline/vim-airline'

### Fern関連
# ファイルツリーを表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
'''
# ファイルツリーにgitの差分を表示
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
# ファイルツリーにフォントを表示
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

# エディタにgitの差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 括弧に色をつける
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# インデントに色をつける
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'

# snipetを提供
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# telescope.nvimでアイコンを表示
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# あいまい検索
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.1'
hook_add = '''
" Ctrl+pでファイル名検索
nnoremap <C-p> <cmd>Telescope find_files<cr>
"Ctrl+gでプロジェクト内のファイルの文字列で検索
nnoremap <C-g> <cmd>Telescope live_grep<cr>
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
function! s:fern_settings() abort
  nmap <silent> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

